environment:
  matrix:
    - nodejs_version: 10

  install: 
    - ps: Install-Product node $env:nodejs_version
    - npm install

  test_scripts:
    - node --version
    - npm --version
    # - npm test
    - npm test:unit

  build: off